<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adult Letter Dashboard</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }
        nav {
            background-color: #333;
            color: white;
            padding: 1rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        nav a {
            color: white;
            text-decoration: none;
            margin: 0 1rem;
        }
        nav a:hover {
            text-decoration: underline;
        }
        .container {
            padding: 2rem;
        }
        .letter, .wishlist {
            margin-bottom: 2rem;
            padding: 1rem;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
        }
        .letter h2, .wishlist h2 {
            margin-top: 0;
        }
    </style>
</head>
<body>
    <nav>
        <div>Dashboard</div>
        <div>
            <a href="index.html">Home</a>
        </div>
    </nav>
    <div class="container">
        <div class="letter">
            <h2>Letter from Children</h2>
            <p id="children-letter">Loading letter...</p>
        </div>
        <div class="wishlist">
            <h2>Wishlist Generated by ChatGPT</h2>
            <ul id="wishlist">
                <li>Loading wishlist...</li>
            </ul>
        </div>
    </div>

    <script>
        // Fetch data from childrenletter.html (simulated here)
        document.addEventListener('DOMContentLoaded', () => {
            // Simulate fetching data from childrenletter.html
            const childrenLetter = "Dear Santa, I have been very good this year. I would like a toy car and a dollhouse. Thank you!";
            document.getElementById('children-letter').textContent = childrenLetter;

            // Simulate fetching data from ChatGPT (this would be replaced with an actual API call)
            const wishlist = [
                { item: "Toy Car", price: "$20", link: "https://example.com/toy-car" },
                { item: "Dollhouse", price: "$50", link: "https://example.com/dollhouse" }
            ];

            const wishlistElement = document.getElementById('wishlist');
            wishlistElement.innerHTML = ''; // Clear loading text
            wishlist.forEach(wish => {
                const listItem = document.createElement('li');
                listItem.innerHTML = `${wish.item} - ${wish.price} - <a href="${wish.link}" target="_blank">Buy here</a>`;
                wishlistElement.appendChild(listItem);
            });
        });
    </script>
</body>
</html>